name: ridewave_mobile
description: RideWave rider & driver Flutter app (skeleton)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  http: ^0.13.0
  provider: ^6.0.0
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
